### ISSUE TITLE
which version of python and ubuntu should I use

### ISSUE THREAD

**Issue by JianWu313** [PRBonn/puma#1]
1.Should I use python  3.6.9 like ubuntu18 default to run your skript.I have noticed that in the embree.sh you have used "pip install" so I just wonder whether to use python2 or python3.
2.Another problem is the trimesh can not detect embree engine even if I have run the embree.sh and installed pyembree successfully.I just can not resolve the api of "trimesh.ray.has_embree", I can also not found it in the official API document and source code. Can I just comment and  ignore it?

**Comment by nachovizzo** [comment]
Please don't use Python2. It has been already deprecated. I use python 3.x, the minor version doesn't make any difference.

If you can't install the embree library then the frame to mesh icp will be extremely slow.

If you want to try out the code I highly recommend to use the provided docket container. It has everything you need without requiring any type of installation

**Comment by JianWu313** [comment]
> Please don't use Python2. It has been already deprecated. I use python 3.x, the minor version doesn't make any difference.
> 
> If you can't install the embree library then the frame to mesh icp will be extremely slow.
> 
> If you want to try out the code I highly recommend to use the provided docket container. It has everything you need without requiring any type of installation

thanks for your quick reply ,I have run it sucessfully with your docker environment. I still have one question: if I want to change the resolution of the mesh,(for example ,I don not need so many faces).where can I edit the parameters of poisson reconstruction

**Comment by nachovizzo** [comment]
You should probably take a look at the official PSR documentation. For this repo you can change the `depth` parameter to 8 or so here:
https://github.com/PRBonn/puma/blob/4a5980fcd302fc794f50e782e478a3bdd77f57b2/puma/mesh/poisson.py#L30

**Comment by Zhangjyhhh** [comment]
could you tell me your envs like ubuntu 18 ,python3.6.9 ...more thing?because when i run in ubuntu 18 with python3.6.9 this item in docker env ,it occur errors
