### ISSUE TITLE
Using docker, PermissionError: [Errno 13] Permission denied: './data/kitti-odometry' ERROR: 1

### ISSUE THREAD

**Issue by RuanJY** [PRBonn/puma#10]
Dear authors,
Thank you for your birlliant work. I am trying to use it based on docker, (linux ubuntu18.04). I set the $DATASETS as followed:
```
ruanjy@ruanjy:~/Workspace/noRosCode_ws/puma/apps$ echo $DATASETS
/home/ruanjy/HDD/dataset_all/kitti_odometry/data_odometry_velodyne
```
and when I run (change the path a liitle) :
```
ruanjy@ruanjy:~/Workspace/noRosCode_ws/puma$ docker-compose run --rm apps bash -c '\
>     ./data_conversion/bin2ply.py \
>     --dataset $DATASETS/dataset/ \
>     --out_dir ./data/kitti-odometry/ply/ \
>     --sequence 07
>     '
```
 I get follwing error:
```
Creating puma_apps_run ... done
Converting .bin scans into .ply fromat from:/data//dataset/ to:./data/kitti-odometry/ply/
Traceback (most recent call last):
  File "./data_conversion/bin2ply.py", line 111, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./data_conversion/bin2ply.py", line 86, in main
    os.makedirs(out_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './data/kitti-odometry'
ERROR: 1
```
I find that I can write something into the folder `/data` with root, but I fail to run the command again with 'sudo', I think that is because the &DATASETS will be reset.  When I switch to root by 'su', I get the same error as before.
I check my user-id and group id are  1000.

Can you help me to figure out the problem? Thank you very much!

**Comment by nachovizzo** [comment]
Hello, thanks for trying out the code.

I guess that the error is `PermissionError: [Errno 13] Permission denied: './data/kitti-odometry'` Meaning that on your local directory you can't access the `'./data/kitti-odometry` directory. This might be related to [docker-linux-post-install](https://docs.docker.com/engine/install/linux-postinstall/) problems. Did you run those post-install steps?

**Comment by RuanJY** [comment]
Thank you for your repley.
I finished the post-install steps and it still doesn't work. But I find that if I add `-u root` then I can access those folders and everything goes well, like 
```
 docker-compose run -u root --rm apps bash  -c '\
    ./data_conversion/bin2ply.py \
    --dataset $DATASETS/dataset/ \
    --out_dir ./data/kitti-odometry/ply/ \
    --sequence 07
    '
```
I am learning about Dockfile now, maybe I can find where the problem derive from.
