### ISSUE TITLE
question about build_gt_cloud.py

### ISSUE THREAD

**Issue by qixuema** [PRBonn/puma#13]
I want to generate the gt point cloud of the street and compare it with the reconstructed model. But when I execute the following code, there are some errors. If you can, please help solve the following problem. I will appreciate it very much!
`docker-compose run --rm apps bash -c '\
    ./pipelines/mapping/build_gt_cloud.py  \
    --dataset ./data/kitti-odometry/ply \
    --sequence 07 \
    --n_scans 40
    '`
![a579f9a863da140b98bfe4452722b1e](https://user-images.githubusercontent.com/58554118/162368781-2d4efe36-07ce-4052-ae3e-8bdfa3e9f523.png)
If this method doesn't work, can you tell me how to generate street gt point cloud?

**Comment by nachovizzo** [comment]
Hello, according to the error msg, it says that there is no ground truth poses available. Are you sure to have the correct poses in the correct place? Where is your data?

**Comment by qixuema** [comment]
I misplaced pose. Now the program can run normally. Thank you again. Your work is so great!
