### ISSUE TITLE
Metrics calculation source code

### ISSUE THREAD

**Issue by creatorofuniverses** [PRBonn/puma#14]
Good afternoon!
Thank you very much for publishing the source code! You have done a great job and proposed a very interesting SLAM approach.
I am particularly interested in your approach to map quality evaluation, it seems to me it is very promising. I would like to reproduce your metrics and evaluate other mapping algorithms. 
Could you please share the source code for map quality estimation?

**Comment by nachovizzo** [comment]
Hello, @VitalyyBezuglyj sorry for the late reply.  I'm happy you find the work useful.

I didn't add the evaluation code to the original implementation but you can find it here: [evaluation.zip](https://github.com/PRBonn/puma/files/8797240/evaluation.zip)


Evaluating mapping quality is still a "hard topic" **for me**. I still couldn't find a metric that somehow explains what you can determine qualitatively with your eyes. Even so, mapping quality is typically more critical for downstream tasks, such as path planning, etc. A "nice-looking" map that is not useful for robotics applications, is just a "nice-looking map".

I hope this helps!

**Comment by creatorofuniverses** [comment]
Thank you very much!

Yes, evaluating quality is indeed a non-trivial task. I think the problem is that the map is an abstraction, a model. The very idea of the map implies that we have omitted some details and left what is important for solving the problem. And so the question about the quality of the map makes sense only in the context of this task.
And, when we try to assess the quality of the map without defining the task, we are trying to determine how good it is for any possible task - that is, how accurate a copy of reality it is :)

From this point of view, since we are building an "absolute" model, probably a good criterion of quality is the customizability/convertibility/interpretability of our model - how easily we can turn an "exact copy" into a "model" corresponding to any task. Although this is a question of the representation model of the map itself, not the specific instance.
