### ISSUE TITLE
performance and speed comparison between Poisson Surface Reconstruction and Ball pivoting

### ISSUE THREAD

**Issue by waveleaf27** [PRBonn/puma#17]
Hi, have you tried Ball pivoting? since Poisson Surface Reconstruction fail in some sequence.
thanks @niosus

**Comment by nachovizzo** [comment]
Hello @waveleaf27,

We did try ball pivoting, but was never giving reasonable results. You can give it a try by using Open3D.

Thanks a lot @niosus

**Comment by waveleaf27** [comment]
thanks for reply. I also wonder that the performance  difference of your two recent work: PUMA and VGBFusion. I want to reconstruct scene for nuscene dataset. @nachovizzo cc @niosus

**Comment by nachovizzo** [comment]
Ah yes, If you want you can use [VDBFusion](https://github.com/PRBonn/vdbfusion). This mapping pipeline works as good as the pose estimates you have (it's mapping with known poses, so you need to provide it).

If you already have the nuSccenes dataset (we have a kitti-ized version) you can use this simple scripts to launch the maping pipeline:

Install dependencies:
```sh
$ pip install vdbfusion
$ git clone https://github.com/PRBonn/vdbfusion
$ cd vdbfusion/examples/python
$ pip install -r requirements.txt
```

Launch the pipeline
```sh
$ ./nuscenes_pipeline.py --sequence 0103 --visualize $DATASETS/nuScenes/kitti_nuscenes/
```

## Results
![image](https://user-images.githubusercontent.com/21349875/202406050-c1479a53-3132-4ab6-83ad-6976719b70b1.png)

And if you need to work with the internal data representation, you can use `vdb_view` to inspect the volume and play around a bit:

![image](https://user-images.githubusercontent.com/21349875/202406417-2377722e-0a4f-472e-a685-08e75e8aadd3.png)
![image](https://user-images.githubusercontent.com/21349875/202406459-e8b5361a-fcb7-4f8e-9b81-2581c60d3fd6.png)

**Comment by waveleaf27** [comment]
thanks for reply, I will try it !

**Comment by waveleaf27** [comment]
can you provide script to generate nuscene dataset(kitti-ized version) using in [VDBFusion](https://github.com/PRBonn/vdbfusion).. Thanks @nachovizzo

**Comment by nachovizzo** [comment]
Done at [e5c9a5d327be632883e59beceafb65217126daf38aae95e8e6b178879efcd076](https://github.com/PRBonn/vdbfusion/commit/88f94a1e8a53d83e603fcc1426f5e1b064bdd4e3#diff-e5c9a5d327be632883e59beceafb65217126daf38aae95e8e6b178879efcd076)
