### ISSUE TITLE
Accurate mapping while localizing

### ISSUE THREAD

**Issue by MigVega** [PRBonn/puma#18]
Hi @nachovizzo,

Thank you for your awesome work and open source code!

From the paper and the code I think is is possible to use PUMA in online localization mode (as mention in the Section IV-E: "Registration Algorithm")
However, I am wondering if it is possible to create an aligned map at the same time and continue mapping even if there is not anymore a map available.
Does PUMA already do that?
If you have any advice for this question, I will be very grateful!

Thanks in advance!

**Comment by nachovizzo** [comment]
Hello @MigVega. Sorry for the delay in the response!

What do you mean with “Online localization”. PUMA is capable to obtain incremental pose estimates(typically called Odometry), which basically means that it can't really do **localization**, but just estimate an incremental pose from the previous one. This basically means that even if you do not have any external pose source, you can still use PUMA to create a map, you can check [this app](https://github.com/PRBonn/puma/blob/main/apps/pipelines/slam/puma_pipeline.py) in case you want to do so.

**Comment by MigVega** [comment]
Hi @nachovizzo,

Thank you for the explanation.

With "online localization", I mean real-time localization in a prior map.

Somehow I thought PUMA could be used for localization as well, but now you've made it clear to me that it's not a feature yet.

Thanks for your work and for answering my question!

**Comment by MigVega** [comment]
N/A
