### ISSUE TITLE
How to run puma on Newer College dataset?

### ISSUE THREAD

**Issue by JunyuanDeng** [PRBonn/puma#19]
Thanks for your work!

I'm running puma on Newer College dataset, but I can't get "complete" mesh results:

I first run with the default config set in `puma.yml`, but the result seems to be incomplete: 
![snapshot01](https://user-images.githubusercontent.com/62542727/218000779-21d84491-9f23-4fcb-8d36-80bc8e41f3e8.png)

The Ground Truth is like this:
![snapshot00](https://user-images.githubusercontent.com/62542727/218000850-eb17a280-87b2-4a08-9e42-3a1ac98beb98.png)

I try to set `min_density` to 0.01, but noting changes. 

And I try with  0 `min_density`, the result become much more strange:
![snapshot00](https://user-images.githubusercontent.com/62542727/218001371-a63c2131-009b-4742-b1e8-cc30d3174901.png)

Another question is about the tracking result. When puma processes on this dataset, it will lose track, here is the tracking result: 
![image](https://user-images.githubusercontent.com/62542727/218002501-b838d44e-fff7-4c50-bb37-590b98842971.png)
The green line is the GT pose, and the blue line is the tracking result.

I change the processing frame gap to 2, meaning that puma processes every two frame (e.g. `00001.pcd`, `00003.pcd`, `00005.pcd` .......), the tracking runs works well:

![image](https://user-images.githubusercontent.com/62542727/218002973-ec620795-449e-4e60-8d88-3577c5171492.png)

What should I do to get a correct and complete result?

**Comment by nachovizzo** [comment]
Before I even reply to your questions,

do you have a particular need for using PUMA? You could use [VDBFusion](https://github.com/PRBonn/vdbfusion) instead, which is drastically faster. For obtaining pose information, you can use [KISS-ICP](https://github.com/PRBonn/kiss-icp). To use these modules, you just need to: **$ pip install kiss-icp** and **$ pip install vdbfusion**

Some eye-candy VDBFusion results:

![image](https://user-images.githubusercontent.com/21349875/218053417-8122640d-f749-49a1-b737-e1b1f7718c30.png)
![image](https://user-images.githubusercontent.com/21349875/218053476-0121d42e-6bb3-4850-b2a2-fb18e4dad9df.png)

**Comment by JunyuanDeng** [comment]
Thanks for your reply!
Yes, I have some particular needs for using PUMA. 
I would appreciate it if you could answer my questions about puma. And I will later also look at your other works.
Best regards,

**Comment by nachovizzo** [comment]
I'm sorry, but I'd say the method fails, I sadly don't have time to look into this.

If you are writing a paper and want to bash puma go ahead, no hard feelings ;) If it fails, it fails. I don't consider this approach a good one for robotics anymore, there is not much better performance than KISS-ICP + VDBFusion. Specially for real world applications, and not academic-syntethic ones.

Thanks for trying our approach, though!!!
