### ISSUE TITLE
Failed to run puma_pipepline on our datasets.

### ISSUE THREAD

**Issue by yutouwd** [PRBonn/puma#2]
Hello there,

I have successfully run the demo on docker. But when I try to run it on two of our datasets, it would have the same error running the ```puma_pipeline```. The error information are as follows:

```
Creating puma_apps_run ... done
Results will be saved to results/kitti-odometry_07_depth_10_cropped_p2l_raycasting.txt
[scan #30] Running PSR over local_map:  74%|█████████████████████▌       [00:04<00:01,  6.67 scans/s]
Traceback (most recent call last):
  File "./pipelines/slam/puma_pipeline.py", line 176, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./pipelines/slam/puma_pipeline.py", line 156, in main
    mesh, _ = create_mesh_from_map(
  File "/usr/local/lib/python3.8/dist-packages/puma/mesh/poisson.py", line 46, in create_mesh_from_map
    return run_poisson(pcd, depth, n_threads, min_density)
  File "/usr/local/lib/python3.8/dist-packages/puma/mesh/poisson.py", line 37, in run_poisson
    vertices_to_remove = densities < np.quantile(densities, min_density)
  File "<__array_function__ internals>", line 5, in quantile
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/function_base.py", line 3930, in quantile
    return _quantile_unchecked(
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/function_base.py", line 3937, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/function_base.py", line 3515, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/function_base.py", line 4050, in _quantile_ureduce_func
    n = np.isnan(ap[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0
ERROR: 1
```

**Comment by nachovizzo** [comment]
That sounds like the reconstruction pipeline output an empty mesh, but I can't tell much than that without looking to the data.

This is the latest step in the puma pipeline before crashing ` vertices_to_remove = densities < np.quantile(densities, min_density)` meaning that basically the `densities` array is empty. You might want to add a check there

**Comment by yutouwd** [comment]
Hello @nachovizzo 

Thanks for you help. Now, I can build out the mesh map. But the map is so weird.

**Corridor**:
mesh map:
![Screenshot from 2021-06-17 10-43-06](https://user-images.githubusercontent.com/6382417/122322932-dd314f00-cf58-11eb-9f39-3e384bc9030b.png)

point cloud map:

![Screenshot from 2021-06-10 17-26-22](https://user-images.githubusercontent.com/6382417/122322985-f1754c00-cf58-11eb-8a7e-087db037c5a3.png)

**Carpark**:
mesh map:
![Screenshot from 2021-06-17 10-44-49](https://user-images.githubusercontent.com/6382417/122323061-123da180-cf59-11eb-8a8d-882b0ff4a46e.png)

![Screenshot from 2021-06-17 10-44-55](https://user-images.githubusercontent.com/6382417/122323067-14076500-cf59-11eb-8410-362d330f841c.png)

point cloud map:
![Screenshot from 2021-06-10 17-23-31](https://user-images.githubusercontent.com/6382417/122323199-4d3fd500-cf59-11eb-9936-8faa8c4315b4.png)

What do you think may be causing the problem?

**Comment by nachovizzo** [comment]
Not really sure, since that mesh doesn't look to have the vertex normals. In my experience, sometimes the mesh looks weird and ugly, but the "main thing" is there. One just needs to find a good way of post-process it. If you can send me the map data I can take a closer look.

**Comment by yutouwd** [comment]
Of course. I have sent a email to you. Thank you so much.

**Comment by nachovizzo** [comment]
So, sadly those maps don't look good at all. There is no hope for the puma pipeline to produce something meaningful if the input point cloud is not precise enough.
Some of the problems I see right away:

 - The map is not dense enough, it looks heavily downsampled. You should avoid this for the meshing algorithm. Once you have the mesh it will be "compressed" enough, so don't worry about the size of the map
 - Looks like there are a lot of dynamics or registration errors. If I look at the part of the "Carpark" map, I couldn't build a 3D model by hand, and I can't really tell how the real world scene looks like
![image](https://user-images.githubusercontent.com/21349875/122915779-6b904100-d35c-11eb-8f02-95520dda217f.png)
 - The map in general looks too sparse, you should try to crop your point clouds. to store the "most interesting" points. If you have 2 points that are 200m away from the rest of the points, you should reject them as outliers

As an example, here is an example of how one good input point cloud map should look. By inspecting the map you can really tell what's present on the scene and what now

| Input | Output|
|:--:|:--:|
|![image](https://user-images.githubusercontent.com/21349875/122916175-e6f1f280-d35c-11eb-99ce-7e0cf501f628.png)|![image](https://user-images.githubusercontent.com/21349875/122916125-d6417c80-d35c-11eb-850c-ffe145a52fb2.png)|

**Comment by yutouwd** [comment]
Thank you so much for your time.

**Comment by cwgan** [comment]
@yutouwd 
Hello friend,
I have the same problem as yours. 
Have you solved this problem, or what other methods have you used for 3D reconstruction？

**Comment by nachovizzo** [comment]
@cwgan I would advise using [vdbfusion](https://github.com/PRBonn/vdbfusion) which is much faster and simpler to use than PUMA. Just `pip install vdbfusion` and start playing around :)

**Comment by cwgan** [comment]
@nachovizzo Thank you very much! I will try on it.
