### ISSUE TITLE
ERROR:139

### ISSUE THREAD

**Issue by NudtCalculus** [PRBonn/puma#21]
Hello there,

I encountered ERROR: 139 while running `puma_pipeline.py` on my own datasets collected from gazebo. 

  [scan #180] Running PSR over local_map:  58%|██▉  [10:49<09:44,  4.50s/ scans][WARNING] /root/Open3D/build/poisson/src/ext_poisson/PoissonRecon/Src/FEMTree.Initialize.inl (Line 193)
          Initialize
          Found bad data: 675972
ERROR: 139

If I only reconstruct on previous frames, it works. Is there a problem with the data at frame scan#180? What are the specific issues and how to avoid?

**Comment by nachovizzo** [comment]
This is an error from the PSR method, I guess there is not much we can do in our side. You can also try to run it single thread ;)

**Comment by NudtCalculus** [comment]
Thanks for your reply.
