### ISSUE TITLE
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

### ISSUE THREAD

**Issue by captain-xuwenqiang** [PRBonn/puma#3]
Hello,I have installed docker and docker compose according to the documentation. In the third step, I try to building the `apss` docker container. I entered 'make' command in the terminal, But error occur as follow:
![2021-06-20 21-50-07屏幕截图](https://user-images.githubusercontent.com/68489582/122676779-0f210a80-d212-11eb-8925-e17e28bee6d0.png)
I entered 'sudo docker-compose' command in the terminal to solve this problem. But error occur as follow:
![2021-06-20 21-57-06屏幕截图](https://user-images.githubusercontent.com/68489582/122676878-7dfe6380-d212-11eb-861f-6615e5d3ea4e.png)
So I come here to search for your help. Thank you.

**Comment by nachovizzo** [comment]
Hello, the problem has a simple solution.

Just follow the [official docker installation instructions](https://docs.docker.com/engine/install/linux-postinstall/) and you will be fine

**Comment by captain-xuwenqiang** [comment]
Hello, @nachovizzo
Thank you for your answer. I have successfully built the `apss` docker container. In the next step, their still some problem as follow:
![2021-06-21 15-29-31屏幕截图](https://user-images.githubusercontent.com/68489582/122724177-450fce80-d2a6-11eb-8738-4e9ddf99d5d0.png)
I don't know what cause this error. May be I set a wrong data-set path. If you think so, please offer me a example. Or others reason? Thank you

**Comment by nachovizzo** [comment]
![image](https://user-images.githubusercontent.com/21349875/122727591-7c1abb80-d277-11eb-8342-051b6da041e9.png)
![image](https://user-images.githubusercontent.com/21349875/122727694-98b6f380-d277-11eb-9e49-9b003eb97a4a.png)
