### ISSUE TITLE
raise "PyEmbree engine not installed, this experiment will never end"

### ISSUE THREAD

**Issue by captain-xuwenqiang** [PRBonn/puma#4]
Hellow, I have install `puma` locally according to (./INSTALL.md). I try to run puma_pipeline.py, the error appears as follows:
![2021-06-26 09-36-48屏幕截图](https://user-images.githubusercontent.com/68489582/123497801-12792380-d662-11eb-9de8-e26b647cb102.png)
I have successfully bash  3rdparty/embree.sh.

**Comment by nachovizzo** [comment]
Hello, I can't say much. The error is quite clear to me, the Embree library has not been properly installed. What you can do is play with a python shell until you get a 'True' value on ` trimesh.ray.has_embree`

```python
In [1]: import trimesh
   ...: 
   ...: trimesh.ray.has_embree
Out[1]: True
```
