### ISSUE TITLE
Questions for the pointcloud Poisson reconstruction.

### ISSUE THREAD

**Issue by jikerWRN** [PRBonn/puma#8]
Thanks for your great work and open code!

In your code, you accumulate 30 scans of point cloud and then perform Poisson reconstruction.  I want to know if I can do it with a scan of point cloud. Or in other words, can I get a good Poisson reconstruction surface using a scan of point cloud? If you have any advices for this question, I will be very grateful!

Thanks in advance!

**Comment by nachovizzo** [comment]
Hello, that's a really good question indeed. And we also asked ourselves the same one. If you try to run Poisson with a single sparse LiDAR point cloud the results will be not good at all. So, not much you can do about it.

The good news is that we have an upcoming work(to be released in the following months) that literally solves this problem on a scan-to-scan basis, outperforming the Poisson method by a big margin.

Keep an eye on our GitHub page, but I will paste the link once we can open-source the project on this issue.

**Comment by jikerWRN** [comment]
Thanks for your reply, looking forward to your new work!

**Comment by nachovizzo** [comment]
@jikerWRN Thanks for the patience, please check https://github.com/PRBonn/vdbfusion
