### ISSUE TITLE
Open3D with GeneralizedICP support not installed, check INSTALL.md

### ISSUE THREAD

**Issue by elegentbamboo** [PRBonn/puma#9]
INFO - 2021-09-29 22:58:32,090 - utils - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO - 2021-09-29 22:58:32,090 - utils - NumExpr defaulting to 8 threads.
Open3D with GeneralizedICP support not installed, check INSTALL.md

I have installed GeneralizedICP suceessfully.why ?

**Comment by nachovizzo** [comment]
Hello, that error doesn't seem to be related to the GeneralizedICP implementation. I can't even say if that's an error or not.
